### ISSUE TITLE
@Order attribute on @GrpcGlobalInterceptor ignored when created by @Bean inside a @Configuration

### ISSUE THREAD

**Issue by seime** [LogNet/grpc-spring-boot-starter#117] opened 2019-04-25 07:39 UTC
The `@Order` annotation is not detected when used inside a `@Configuration` and hence the order is undefined (on my JRE the interceptor defined by the last factory method is executed first)

Example: 
```
@Configuration
 public class MyConfig{
     @Bean
     @Order(1) // Ignored
     @GRpcGlobalInterceptor
     public  ServerInterceptor first(){
         return new ServerInterceptor(){ ..} // Executed last
     }

     @Bean
     @Order(2) // Ignored
     @GRpcGlobalInterceptor
     public  ServerInterceptor last(){ 
         return new ServerInterceptor(){ ..} // Executed first
     }
 }
```

**Comment by jvmlet** [comment] 2019-04-25 07:49
Are you able to reproduce by running   [this](https://github.com/LogNet/grpc-spring-boot-starter/blob/master/grpc-spring-boot-starter-demo/src/test/java/org/lognet/springboot/grpc/OrderedInterceptorsTest.java) test ?

**Comment by jvmlet** [comment] 2019-04-25 08:04
Sorry, overlooked that your case is different, was able to reproduce, will be fixed.

**Comment by jvmlet** [comment] 2019-04-25 12:00
It's no so easy with `spring-boot:1.5.13`  and  `spring:4.3.17`. Since  I don't want to drop support of `1.5.X`, please use [this](https://github.com/LogNet/grpc-spring-boot-starter/blob/master/grpc-spring-boot-starter-demo/src/test/java/org/lognet/springboot/grpc/OrderedInterceptorsTest.java#L67) workaround  meanwhile.

**Comment by asinbow** [comment] 2020-07-01 11:11
It's a bug of the customized re-sorting.
https://github.com/LogNet/grpc-spring-boot-starter/blob/f959ae4ba1e81232c2a56637f6ce27217009e564/grpc-spring-boot-starter/src/main/java/org/lognet/springboot/grpc/GRpcServerRunner.java#L122

![image](https://user-images.githubusercontent.com/731874/86237398-45fbac00-bbce-11ea-9191-a155b4dbf859.png)

**Comment by jvmlet** [comment] 2020-07-01 12:06
This is also supported 
```java
@Configuration
    pubic class MyConfig{
        @Bean
        @GRpcGlobalInterceptor
        @Order(-1)
        public ServerInterceptor myInterceptor(){

        }
    }
```

**Comment by seime** [comment] 2020-10-22 09:27
> Since I don't want to drop support of `1.5.X`

Spring Boot end of life was august 2019 - maybe it is time to drop support for it? https://spring.io/blog/2018/07/30/spring-boot-1-x-eol-aug-1st-2019

**Comment by jvmlet** [comment] 2020-10-22 09:43
I was dropped science  `4.0.0`

**Comment by skjolber** [comment] 2020-12-11 11:48
And progress on this?

**Comment by jvmlet** [comment] 2020-12-11 13:36
Not yet, but your interceptor can implement Ordered interface

**Comment by skjolber** [comment] 2021-01-22 11:43
So basically this forces me to either use all the global interceptors (and no interceptors specified on the service), or use no global interceptors (specifing interceptors explicitly on the service). Ordered does not really work that well, however for reuse, creating a custom annotation with @GrpcService should work.

**Comment by jvmlet** [comment] 2021-01-22 12:06
What do you mean by `Ordered does not really work that well` ?  Either it works or not. If you have the case that reproduces the out of order execution when interceptor implements Ordered interface, please provide the scenario

**Comment by skjolber** [comment] 2021-01-22 12:20
Sorry, I meant does not really work that well for me, as interceptors from third party libraries like `TransmitStatusRuntimeExceptionInterceptor` does not implement Ordered.

**Comment by jvmlet** [comment] 2021-01-22 12:53
The fasters solution  I see is to wrap 3rd party interceptor with yours `proxy` and let proxy to implement Ordered.
 I'll do my best to resolve this.

**Comment by jvmlet** [comment] 2021-01-22 13:06
BTW, if you are trying to propagate the validation error, the starter supports spring validation integration.

**Closed** 2021-01-25 12:49 UTC
